# Generated by Django 4.2.13 on 2024-05-30 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bikeStation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.TextField()),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField()),
                (
                    "station_no",
                    models.ForeignKey(
                        db_column="station_no",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bikeStation.bikestationinfo",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
