# Generated by Django 4.2.13 on 2024-05-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BikeStationInfo",
            fields=[
                (
                    "station_no",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("station_name", models.CharField(max_length=500)),
                ("station_area", models.CharField(max_length=500)),
                ("station_address", models.CharField(max_length=500)),
                ("station_area_en", models.CharField(max_length=500)),
                ("station_name_en", models.CharField(max_length=500)),
                ("station_address_en", models.CharField(max_length=500)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("act", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="BikeStationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mday", models.DateTimeField()),
                ("srcUpdateTime", models.DateTimeField()),
                ("updateTime", models.DateTimeField()),
                ("infoTime", models.DateTimeField()),
                ("infoDate", models.DateField()),
                ("total", models.IntegerField()),
                ("available_rent_bikes", models.IntegerField()),
                ("available_return_bikes", models.IntegerField()),
                (
                    "station_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bikeStation.bikestationinfo",
                    ),
                ),
            ],
        ),
    ]
